from __future__ import annotations

import argparse

from services.proxy_workflow_service import ProxyWorkflowService


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run the unified proxy collection, normalization, checking, and persistence workflow.")
    parser.add_argument("--skip-crawl", action="store_true", help="Do not refresh the embedded Deadpool seed files before checking.")
    parser.add_argument("--skip-deadpool-sources", action="store_true", help="Ignore proxy source files generated by the embedded Deadpool project.")
    parser.add_argument("--skip-db", action="store_true", help="Run checks without saving results to MySQL.")
    parser.add_argument("--max-workers", type=int, default=150, help="Maximum number of concurrent proxy checks.")
    return parser


if __name__ == "__main__":
    args = build_parser().parse_args()
    summary = ProxyWorkflowService().run_automated_workflow(
        refresh_external_sources=not args.skip_crawl,
        include_deadpool_sources=not args.skip_deadpool_sources,
        max_workers=args.max_workers,
        save_to_db=not args.skip_db,
    )
    print(f"Collected {summary['collectedCount']} unique proxies from {summary['sourceCount']} sources.")
    print(f"Canonical dataset written to: {summary['canonicalFile']}")
    print(f"JSON dataset written to: {summary['jsonFile']} ({summary['jsonRecordCount']} records)")
    print(f"Check completed: {summary['aliveCount']} proxies are alive.")
    if summary["refreshSummary"] is not None:
        refresh = summary["refreshSummary"]
        print(f"Deadpool refresh status: {refresh['status']}")
        if refresh.get("returnCode") is not None:
            print(f"Deadpool refresh exit code: {refresh['returnCode']}")
