-- Phase 0 draft migration. Creates security scan batch task records.

CREATE TABLE security_scan_batches (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    batch_id CHAR(36) NOT NULL,
    scan_mode VARCHAR(64) NOT NULL DEFAULT 'honeypot',
    scan_policy VARCHAR(64) NOT NULL DEFAULT 'funnel_standard',
    max_scan_depth VARCHAR(32) NOT NULL DEFAULT 'standard',
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    target_proxy_count INT NOT NULL DEFAULT 0,
    checked_proxy_count INT NOT NULL DEFAULT 0,
    skipped_proxy_count INT NOT NULL DEFAULT 0,
    error_proxy_count INT NOT NULL DEFAULT 0,
    normal_proxy_count INT NOT NULL DEFAULT 0,
    suspicious_proxy_count INT NOT NULL DEFAULT 0,
    malicious_proxy_count INT NOT NULL DEFAULT 0,
    anomaly_event_count INT NOT NULL DEFAULT 0,
    light_scan_count INT NOT NULL DEFAULT 0,
    standard_scan_count INT NOT NULL DEFAULT 0,
    deep_scan_count INT NOT NULL DEFAULT 0,
    browser_scan_count INT NOT NULL DEFAULT 0,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    elapsed_seconds DOUBLE NULL,
    parameters JSON NULL,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_security_batch_id (batch_id),
    KEY idx_security_scan_batches_status (status),
    KEY idx_security_scan_batches_policy (scan_policy),
    KEY idx_security_scan_batches_started_at (started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
