from __future__ import annotations

from core.interfaces import BaseProxySourceProvider, ProxySourceDefinition

from collectors.defaults import DEFAULT_LAST_DATA_PATH, DEADPOOL_GIT_PATH, DEADPOOL_HTTP_PATH, DEADPOOL_LAST_DATA_PATH


class DefaultProxySourceProvider(BaseProxySourceProvider):
    def __init__(self, include_deadpool: bool = True):
        self.include_deadpool = include_deadpool

    def list_sources(self) -> list[ProxySourceDefinition]:
        sources = [
            ProxySourceDefinition(
                name="lastData",
                kind="file",
                location=str(DEFAULT_LAST_DATA_PATH),
                description="Default local proxy dataset used by the checker pipeline.",
                metadata={
                    "format": "ip:port source_name",
                    "extensible_kinds": ["file", "http_api", "feed", "crawler", "plugin"],
                },
            )
        ]
        if self.include_deadpool:
            sources.extend(
                [
                    ProxySourceDefinition(
                        name="deadpool_lastData",
                        kind="file",
                        location=str(DEADPOOL_LAST_DATA_PATH),
                        description="Imported proxy entries generated by the embedded Deadpool crawler project.",
                        metadata={"format": "ip:port [source]", "source_group": "deadpool"},
                    ),
                    ProxySourceDefinition(
                        name="deadpool_http",
                        kind="file",
                        location=str(DEADPOOL_HTTP_PATH),
                        description="HTTP proxy seed list refreshed by the embedded Deadpool crawler.",
                        metadata={"format": "ip:port source_name", "source_group": "deadpool"},
                    ),
                    ProxySourceDefinition(
                        name="deadpool_git",
                        kind="file",
                        location=str(DEADPOOL_GIT_PATH),
                        description="SOCKS5 proxy seed list refreshed by the embedded Deadpool crawler.",
                        metadata={"format": "ip:port source_name", "source_group": "deadpool"},
                    ),
                ]
            )
        return sources
